[@@@ai_disclosure "ai-assisted"]
[@@@ai_model "claude-opus-4-6"]
[@@@ai_provider "Anthropic"]

let ( / ) = Filename.concat

(* Canonicalise [p] to an absolute path. Relative paths in OCAMLFIND_CONF /
   OCAMLLIB break dune (Path.External.of_string rejects them). Falls back to
   the original string if the path does not yet exist on disk. *)
let canonical p = try Unix.realpath p with Unix.Unix_error _ -> p

(* -- OCaml-specific environment ------------------------------------------ *)

let env_vars ?toolchain ~prefix ~dune_cache_root () =
  let prefix = canonical prefix in
  Opam_ctx.switch_env ?toolchain ~prefix ()
  @ [
      ("OCAMLFIND_DESTDIR", prefix / "lib");
      ("DUNE_CACHE", "enabled");
      ("DUNE_CACHE_ROOT", dune_cache_root);
      ("DUNE_CACHE_STORAGE_MODE", "hardlink");
    ]

let envrc_content ?toolchain ~prefix ?tools ~dune_cache_root () =
  let prefix = canonical prefix in
  let tools = Option.map canonical tools in
  let switch_vars =
    List.map
      (fun (k, v) -> Fmt.str "export %s=\"%s\"" k v)
      (Opam_ctx.switch_env ?toolchain ~prefix ())
  in
  let header =
    [
      "# Generated by oi sync — do not edit";
      Fmt.str "OI_PREFIX=$(expand_path %s)" prefix;
      Fmt.str "OI_CACHE=$(expand_path %s)" dune_cache_root;
    ]
    @ (match tools with
      | None -> []
      | Some t -> [ Fmt.str "OI_TOOLS=$(expand_path %s)" t ])
    @ [ "" ]
  in
  (* Tools bin goes first so dev binaries shadow stale host copies; the
     project prefix follows so the main deps' binaries win over system
     PATH. Toolchain [bin] goes AFTER the project prefix so the
     project's own ocamlc (if any) wins over the toolchain's — but in
     practice the project prefix is empty of compiler binaries and the
     toolchain supplies them. *)
  let path_adds =
    (match tools with None -> [] | Some _ -> [ "PATH_add \"$OI_TOOLS/bin\"" ])
    @ [ "PATH_add \"$OI_PREFIX/bin\"" ]
    @
    match toolchain with
    | None | Some { Opam_ctx.relocatable = true; _ } -> []
    | Some (tc : Opam_ctx.toolchain) ->
        [ Fmt.str "PATH_add \"%s/bin\"" tc.install_prefix ]
  in
  String.concat "\n"
    (header @ path_adds @ switch_vars
    @ [
        Fmt.str "export OCAMLFIND_DESTDIR=\"$OI_PREFIX/lib\"";
        "export DUNE_CACHE=enabled";
        Fmt.str "export DUNE_CACHE_ROOT=\"$OI_CACHE\"";
        "export DUNE_CACHE_STORAGE_MODE=hardlink";
        "";
      ])

let make_env ?toolchain ~prefix ?tools ~dune_cache_root () =
  let vars = env_vars ?toolchain ~prefix ~dune_cache_root () in
  let dominated =
    "PATH" :: List.map (fun (k, _) -> String.uppercase_ascii k) vars
  in
  let has_prefix s k =
    let k = k ^ "=" in
    String.length s >= String.length k
    && String.uppercase_ascii (String.sub s 0 (String.length k)) = k
  in
  let current_path =
    try Sys.getenv "PATH" with Not_found -> "/usr/bin:/bin"
  in
  let base =
    Unix.environment () |> Array.to_list
    |> List.filter (fun s -> not (List.exists (has_prefix s) dominated))
  in
  let tools_bin = Option.map (fun t -> canonical t / "bin") tools in
  let toolchain_bin =
    match toolchain with
    | None | Some { Opam_ctx.relocatable = true; _ } -> None
    | Some (tc : Opam_ctx.toolchain) -> Some (tc.install_prefix / "bin")
  in
  (* PATH precedence: [tools/bin] > [prefix/bin] > [toolchain/bin] >
     existing PATH. Tools (dev tooling) shadow the project; the
     project shadows the toolchain so a project-built ocamlc wins if
     present; the toolchain provides what the project doesn't. *)
  let path_components =
    List.filter_map Fun.id [ tools_bin; Some (prefix / "bin"); toolchain_bin ]
  in
  let path_entry =
    "PATH=" ^ String.concat ":" path_components ^ ":" ^ current_path
  in
  let env_pairs = path_entry :: List.map (fun (k, v) -> k ^ "=" ^ v) vars in
  Array.of_list (env_pairs @ base)
