(** Dockerfile generation for [oi docker].

    Emits a standalone static musl build of [oi] on alpine (for CI / manual
    release builds) plus one runnable per-distro image that curls the latest
    [oi] binary from the GitHub releases page and ships the target's depexts.
    The actual [oi build --all --export /out] invocation lives in
    [docker-compose.yml] as a [command:] override, so the same image can run
    against different reporepo pins without rebuilding. *)

module Distro = Dockerfile_opam.Distro

val dockerfile_oi : src_context:string -> Dockerfile.t
(** [dockerfile_oi ~src_context] emits a Dockerfile that builds a static
    musl-linked [oi] binary from the source tree at [src_context] (relative to
    the build context) and exports it as a scratch image at [/oi]. *)

val dockerfile_one_distro :
  ?overlay_depexts:string list -> Distro.t -> Dockerfile.t
(** Per-distro build image. Installs the generic build toolchain (compilers,
    headers, [curl]) together with [overlay_depexts] (the union of [depexts:]
    declared across every reporepo handle: solved root closures for handles with
    [x-root-packages] / [x-oi-toolchain-roots], and every package in the
    overlay's clone for handles that declare neither — see
    {!Build.compute_overlay_depexts_per_distro}). It then fetches the latest
    statically linked [oi-linux-<arch>] and [oix-linux-<arch>] from the [oi]
    GitHub releases page and sets [/work] as the working directory. No [CMD] is
    set: the compose file drives the build+export steps. *)

val dockerfile_project :
  ?overlay_depexts:string list ->
  ?cmd:string ->
  ?generator:string ->
  Distro.t ->
  Dockerfile.t
(** Project-mode Dockerfile: same distro stage as {!dockerfile_one_distro}, plus
    [WORKDIR /src], [COPY . /src], and [RUN cmd] (default [oi build]). Used by
    [oi build --docker] and [oi test --docker]. [generator] customises the
    leading "Generated by ..." comment. *)

type opam_vars = {
  os_distribution : string;
  os_family : string;
  os_version : string;
}

val opam_vars_of_distro : Distro.t -> opam_vars
(** Map a supported docker distribution to the opam platform variables its opam
    filters expect. [os-family] follows opam's conventions ([debian], [rhel],
    [alpine], [suse], [arch]), [os-distribution] is the per-distro name
    ([ubuntu], [fedora], etc.), and [os-version] is the release string taken
    from the [Distro.t] tag. [os] is always [linux] for the distros this
    function supports. *)

val one_distro_filename : Distro.t -> string
(** Filename (without directory) for a per-distro Dockerfile, e.g.
    [Dockerfile.alpine-3.23]. *)

val docker_compose_yaml :
  distros:Distro.t list -> registry_host_path:string -> unit -> string
(** [docker_compose_yaml ~distros ~registry_host_path ()] emits a compose file
    whose services each bind-mount [registry_host_path] at [/out] and run
    [oi build --refresh --all --export /out]. Every container owns its own oi
    state — [oi] auto-clones the reporepo from its configured default URL
    (overridable via [OI_REPOREPO_URL] in the service environment) on first use
    — so containers are independent and safe to run in parallel. Layers are
    tagged with their overlay handle and version in the per-distro sqlite index
    so clients can scope queries to a specific overlay.

    Each service is generated with [OI_BUILD_PARALLELISM=$(nproc)] in its
    command and a high [nofile] ulimit so the in-container build uses every
    available CPU rather than the [min cpu_count 8] default that
    {!D10ir.Config.default} applies for macOS fd-limit safety. Suitable for
    many-core hosts. *)

val write_dockerfile : string -> Dockerfile.t -> unit
(** Serialise a {!Dockerfile.t} to [path] in Dockerfile syntax. *)

val write_file : string -> string -> unit
(** Write arbitrary string contents to [path]. *)

(** {1 Distro depext primitives}

    Exposed for {!Docker_target} (target-mode Dockerfiles), which renders its
    own template rather than going through {!dockerfile_one_distro} but still
    needs the same base build depexts and install command. *)

val build_depexts : [ `Apk | `Apt | `Yum ] -> string
(** Space-separated bootstrap toolchain (compiler, [pkg-config], [m4], [git],
    [curl], …) needed before any opam-driven build can run. Library [-dev]
    depexts live in the opam packages' own [depexts:] and flow in via
    [compute_overlay_depexts] — they are NOT listed here. *)

val install_cmd : [ `Apk | `Apt | `Yum ] -> string -> string
(** [install_cmd mgr pkgs] is the full shell command to install [pkgs] under
    package manager [mgr], including any cache cleanup. *)
